"""Count which protocols each frozen model has been run under, and its headline score.

The table is computed from the versioned run artifacts (seed 42 only), so the report and the
slides never depend on a hand-written coverage claim. Missing cells mean *not run*; no score is
imputed.

    python scripts/protocol_coverage.py
    python scripts/protocol_coverage.py --markdown reports/protocol_coverage.md \
        --json reports/protocol_coverage.json
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd  # noqa: E402

from nlbse24.evaluation.results import results_dataframe  # noqa: E402

PROTOCOLS = ("cv", "pooled_cv", "loo", "official")
PROTOCOL_LABELS = {
    "cv": "Repo-specific CV",
    "pooled_cv": "Pooled CV",
    "loo": "LOO",
    "official": "Official",
}
# Number of repository evaluations a complete run contains: 5 repositories x 5 folds for CV
# and pooled CV, 5 repositories x 1 for LOO and official evaluation.
EXPECTED = {"cv": 25, "pooled_cv": 25, "loo": 5, "official": 5}

# Frozen configurations compared in the report: (artifact run name, display name, owner).
FROZEN_MODELS = (
    ("tfidf_logistic_regression", "TF-IDF + Logistic Regression", "P1"),
    ("tfidf_word_linear_svc", "Word LinearSVC", "P2"),
    ("tfidf_char_linear_svc", "Word + Char LinearSVC", "P2"),
    ("fasttext_style_sgd", "Hashed SGD", "P2"),
    ("fasttext_supervised", "Supervised fastText", "P2"),
    ("tfidf_word_complement_nb", "Complement NB", "P2"),
    ("roberta_base_full", "RoBERTa full fine-tuning", "P3"),
    ("roberta_base_adapter", "RoBERTa LoRA", "P3"),
    ("setfit_mpnet", "SetFit MPNet", "P4"),
    ("setfit_minilm", "SetFit MiniLM", "P4"),
)


def coverage_table(frame: pd.DataFrame, seed: int = 42) -> list[dict[str, object]]:
    """Return one row per frozen model with evaluation counts and balanced macro-F1."""

    frame = frame[frame["seed"] == seed]
    rows: list[dict[str, object]] = []
    for run_name, display, owner in FROZEN_MODELS:
        row: dict[str, object] = {"model": run_name, "name": display, "owner": owner}
        for protocol in PROTOCOLS:
            subset = frame[(frame["model"] == run_name) & (frame["protocol"] == protocol)]
            subset = subset.drop_duplicates(["repository", "fold"])
            count = len(subset)
            if count:
                per_repository = subset.groupby("repository")["macro_f1"].mean()
                score = round(float(per_repository.mean()), 4)
            else:
                score = None
            row[protocol] = {
                "evaluations": count,
                "expected": EXPECTED[protocol],
                "complete": count == EXPECTED[protocol],
                "macro_f1": score,
            }
        rows.append(row)
    return rows


def _cell(cell: dict[str, object]) -> str:
    if not cell["evaluations"]:
        return "not run"
    text = f"{cell['macro_f1']:.4f}"
    if not cell["complete"]:
        text += f" (partial {cell['evaluations']}/{cell['expected']})"
    return text


def render_markdown(rows: list[dict[str, object]]) -> str:
    header = "| Model | Owner | " + " | ".join(PROTOCOL_LABELS[p] for p in PROTOCOLS) + " |"
    divider = "|---|---|" + "---:|" * len(PROTOCOLS)
    lines = [
        "# Protocol coverage (seed 42)",
        "",
        "Repository-balanced macro-F1 per protocol, computed from the versioned run artifacts "
        "(`python scripts/protocol_coverage.py`). `not run` means no artifacts exist; nothing "
        "is imputed. Scores from different protocols answer different questions and must not "
        "be ranked against each other.",
        "",
        header,
        divider,
    ]
    for row in rows:
        cells = " | ".join(_cell(row[p]) for p in PROTOCOLS)  # type: ignore[arg-type]
        lines.append(f"| {row['name']} | {row['owner']} | {cells} |")
    lines.append("")
    return "\n".join(lines)


def render_latex(rows: list[dict[str, object]]) -> str:
    """Booktabs table for the report; the best score in each protocol column is bold."""

    best: dict[str, float] = {}
    for protocol in PROTOCOLS:
        scores = [
            row[protocol]["macro_f1"]  # type: ignore[index]
            for row in rows
            if row[protocol]["macro_f1"] is not None  # type: ignore[index]
        ]
        if scores:
            best[protocol] = max(scores)
    header = (
        r"\textbf{Model} & \textbf{CV} & \textbf{Pooled CV} & \textbf{LOO} "
        r"& \textbf{Official} \\"
    )
    lines = [
        "% Generated by scripts/protocol_coverage.py; do not edit by hand.",
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        header,
        r"\midrule",
    ]
    for row in rows:
        cells = []
        for protocol in PROTOCOLS:
            cell = row[protocol]  # type: ignore[index]
            if not cell["evaluations"]:
                cells.append("--")
                continue
            text = f"{cell['macro_f1']:.4f}"
            if not cell["complete"]:
                text += "$^{*}$"
            if cell["macro_f1"] == best[protocol]:
                text = r"\textbf{" + text + "}"
            cells.append(text)
        lines.append(f"{row['name']} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir", type=Path, default=Path("results"))
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--markdown", type=Path)
    parser.add_argument("--json", type=Path)
    parser.add_argument("--latex", type=Path, help="write a booktabs table for the report")
    args = parser.parse_args(argv)

    frame = results_dataframe(args.results_dir, validate=False)
    rows = coverage_table(frame, args.seed)
    markdown = render_markdown(rows)
    print(markdown)
    if args.markdown:
        args.markdown.write_text(markdown, encoding="utf-8")
    if args.latex:
        args.latex.write_text(render_latex(rows), encoding="utf-8")
    if args.json:
        args.json.write_text(json.dumps(rows, indent=2, ensure_ascii=False), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
